spring:
  application:
    name: backend

  data:
    mongodb:
      uri: mongodb://localhost:27017/smart_campus_db

  web:
    cors:
      allowed-origins: "http://localhost:5173"

server:
  port: 8080
